# Generated by Django 4.1.5 on 2024-05-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
    ]
