# Generated by Django 4.1.5 on 2024-05-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240517_0142'),
    ]

    operations = [
    ]
