# Generated by Django 4.1.5 on 2024-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='credits',
        ),
        migrations.AlterField(
            model_name='attendancecheckin',
            name='presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
