# Generated by Django 4.1.5 on 2024-05-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_attendance_attendancecheckin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='slip',
        ),
    ]
