# Generated by Django 4.1.5 on 2024-05-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_ticket_degree_ticket_department_ticket_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
